//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Dim_Products
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<short> Id_Brand { get; set; }
        public string BrandName { get; set; }
        public Nullable<short> Id_Group { get; set; }
        public string GroupName { get; set; }
        public Nullable<short> Id_Category { get; set; }
        public string Category { get; set; }
        public Nullable<short> Id_SubCategory { get; set; }
        public string SubCatName { get; set; }
        public string Id_Customer { get; set; }
        public string CodeBars { get; set; }
        public string Id_Vendor { get; set; }
        public string VendorName { get; set; }
        public string BuyUnitMsr { get; set; }
        public Nullable<decimal> NumInBuy { get; set; }
        public Nullable<short> ID_Company { get; set; }
    }
}
