//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand_competitors
    {
        public int ID_competitor { get; set; }
        public string Name { get; set; }
        public string ID_customer { get; set; }
        public string Costumer_name { get; set; }
        public string ID_brand { get; set; }
        public string Brand_name { get; set; }
    }
}
