//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ROUTE
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<short> U_Frequency { get; set; }
        public string U_CardCode { get; set; }
        public string U_Route { get; set; }
    }
}
