//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Marketing_Activity
    {
        public int ID_detail { get; set; }
        public string ID_store { get; set; }
        public string store { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_Visit { get; set; }
        public string Cliente { get; set; }
        public string Marca { get; set; }
        public string Categoria { get; set; }
        public string SubCategoria { get; set; }
        public string Producto { get; set; }
        public string Disponible { get; set; }
        public string NoDisponible { get; set; }
        public Nullable<double> PrecioSugerido { get; set; }
        public Nullable<double> PrecioTienda { get; set; }
    }
}
