//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosDemos_20
    {
        public int ID_detail { get; set; }
        public Nullable<int> ID_demo { get; set; }
        public string Id_Store { get; set; }
        public string Store { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public string UserName { get; set; }
        public string IDCliente { get; set; }
        public string Cliente { get; set; }
        public string Marcas { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad_entregado { get; set; }
        public Nullable<decimal> Inventario_inicial { get; set; }
        public string Unidades_Disponibles { get; set; }
        public string Presentacion { get; set; }
        public string Tipo_empaque { get; set; }
        public string Promocion { get; set; }
        public string Descuento { get; set; }
        public string Regalia { get; set; }
        public string Competencia_directa { get; set; }
        public string ComentarioSabor { get; set; }
        public string ComentarioCalidad { get; set; }
        public string ComentarioPrecio { get; set; }
        public string ComentarioEmpaque { get; set; }
    }
}
