//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Audit_2
    {
        public string Id_Store { get; set; }
        public string Store { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> Visit_Date { get; set; }
        public Nullable<int> Id_Visit { get; set; }
        public string Cliente { get; set; }
        public string Marca { get; set; }
        public string SubCategoria { get; set; }
        public string Producto { get; set; }
        public string ProductoDescripcion { get; set; }
        public Nullable<int> Disponible { get; set; }
        public Nullable<int> Promocionado { get; set; }
        public Nullable<double> Precio { get; set; }
        public int ID_detail { get; set; }
    }
}
