//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Audit_11
    {
        public int ID_detail { get; set; }
        public string ID_store { get; set; }
        public string store { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
        public string Proveedor { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Id_Visit { get; set; }
        public Nullable<int> Disponibilidad { get; set; }
        public string Promocionado { get; set; }
        public Nullable<double> Precio { get; set; }
    }
}
