//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demos
    {
        public int ID_demo { get; set; }
        public string ID_Vendor { get; set; }
        public string vendor { get; set; }
        public string ID_brands { get; set; }
        public string Brands { get; set; }
        public string ID_Store { get; set; }
        public string store { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string state { get; set; }
        public System.DateTime visit_date { get; set; }
        public int ID_userCreate { get; set; }
        public int ID_userEnd { get; set; }
        public string ID_ExternalUser { get; set; }
        public int ID_demostate { get; set; }
        public string comments { get; set; }
        public int ID_formM { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime check_in { get; set; }
        public string geoLong { get; set; }
        public string geoLat { get; set; }
        public decimal extra_hours { get; set; }
        public int ID_empresa { get; set; }
        public string UserName { get; set; }
    
        public virtual Demo_state Demo_state { get; set; }
    }
}
