//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estructura_1_1_Comercia
    {
        public string ID_store { get; set; }
        public string store { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
        public Nullable<int> Id_Visit { get; set; }
        public string Cliente { get; set; }
        public string Marca { get; set; }
        public string Linea { get; set; }
        public string PrincipalCompetidor { get; set; }
        public string TomarFotografiaInicial { get; set; }
        public Nullable<decimal> CarasEnTiendaGeneral { get; set; }
        public Nullable<decimal> CarasEnTiendaLinea { get; set; }
        public Nullable<decimal> AproxCajasVentaCategMes { get; set; }
        public string ProductoExhibido { get; set; }
        public string ProductoOrganizadoLimpio { get; set; }
        public string GondolaDry { get; set; }
        public string GondolaPuerta { get; set; }
        public string CoolerAbierto { get; set; }
        public string UbicacionTiendaFoto { get; set; }
        public string UbicacionTiendaFoto2 { get; set; }
        public string UbicacionTiendaFoto3 { get; set; }
        public string PrecioCorrecto { get; set; }
        public string EspaciosAdicionalesTienda { get; set; }
        public string EndCap { get; set; }
        public Nullable<decimal> EndCapCuantos { get; set; }
        public string EndCapFoto { get; set; }
        public string EndCapFoto2 { get; set; }
        public string DropPallet { get; set; }
        public Nullable<decimal> DropPalletCuantos { get; set; }
        public string DropPalletFoto { get; set; }
        public string DropPalletFoto2 { get; set; }
        public string Ganchera { get; set; }
        public Nullable<decimal> GancheraCuantos { get; set; }
        public string GancheraFoto { get; set; }
        public string GancheraFoto2 { get; set; }
        public string Shipper { get; set; }
        public Nullable<decimal> ShipperCuantos { get; set; }
        public string ShipperFoto { get; set; }
        public string ShipperFoto2 { get; set; }
        public string RackMetalico { get; set; }
        public Nullable<decimal> RackMetalicoCuantos { get; set; }
        public string RackMetalicoFoto { get; set; }
        public string RackMetalicoFoto2 { get; set; }
        public string SpinPack { get; set; }
        public Nullable<decimal> SpinPackCuantos { get; set; }
        public string SpinPackFoto { get; set; }
        public string SpinPackFoto2 { get; set; }
        public string Cooler { get; set; }
        public Nullable<decimal> CoolerCuantos { get; set; }
        public string CoolerFoto { get; set; }
        public string CoolerFoto2 { get; set; }
        public string Freezer { get; set; }
        public Nullable<decimal> FreezerCuantos { get; set; }
        public string FreezerFoto { get; set; }
        public string FreezerFoto2 { get; set; }
        public string Bin { get; set; }
        public Nullable<decimal> BinCuantos { get; set; }
        public string BinFoto { get; set; }
        public string BinFoto2 { get; set; }
        public string CrossMerchandising { get; set; }
        public Nullable<decimal> CrossMerchandisingCuantos { get; set; }
        public string CrossMerchandisingFoto { get; set; }
        public string CrossMerchandisingFoto2 { get; set; }
        public string HayHerramientasDisplay { get; set; }
        public string HayHerramientasDisplayPreciadores { get; set; }
        public string HayHerramientasDisplayStickers { get; set; }
        public string HayHerramientasDisplayFloorStickers { get; set; }
        public string HayHerramientasDisplayAfiches { get; set; }
        public string HayHerramientasDisplayChannelStrips { get; set; }
        public string HayHerramientasDisplayFoto { get; set; }
        public string EspaciosAdicionales { get; set; }
        public string EspaciosAdicionalesEndCap { get; set; }
        public string EspaciosAdicionalesEndCapFoto { get; set; }
        public string EspaciosAdicionalesDropPallet { get; set; }
        public string EspaciosAdicionalesDropPalletFoto { get; set; }
        public string EspaciosAdicionalesGanchera { get; set; }
        public string EspaciosAdicionalesGancheroFoto { get; set; }
        public string EspaciosAdicionalesShipper { get; set; }
        public string EspaciosAdicionalesShipperFoto { get; set; }
        public string EspaciosAdicionalesRackMetalico { get; set; }
        public string EspaciosAdicionalesRackMetalicoFoto { get; set; }
        public string EspaciosAdicionalesSpinPack { get; set; }
        public string EspaciosAdicionalesSpinRackFoto { get; set; }
        public string EspaciosAdicionalesCooler { get; set; }
        public string EspaciosAdicionalesCoolerFoto { get; set; }
        public string EspaciosAdicionalesFreezer { get; set; }
        public string EspaciosAdicionalesFreezerFoto { get; set; }
        public string EspaciosAdicionalesBin { get; set; }
        public string EspaciosAdicionalesBinFoto { get; set; }
        public string EspaciosAdicionalesOtro { get; set; }
        public string EspaciosAdicionalesOtroFoto { get; set; }
        public string ActividadesPromocionales { get; set; }
        public string TipoActividadTiene { get; set; }
        public string FotoCompetencia { get; set; }
        public string ComoCerroNegociacion { get; set; }
        public string CondicionFinalTienda { get; set; }
        public string Firma { get; set; }
        public int ID_detail { get; set; }
    }
}
