//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsM_detailsDemos
    {
        public int ID_details { get; set; }
        public int ID_formresourcetype { get; set; }
        public string fsource { get; set; }
        public string fdescription { get; set; }
        public int fvalue { get; set; }
        public decimal fvalueDecimal { get; set; }
        public string fvalueText { get; set; }
        public int ID_formM { get; set; }
        public int ID_visit { get; set; }
        public bool original { get; set; }
        public int obj_order { get; set; }
        public int obj_group { get; set; }
        public int idkey { get; set; }
        public int parent { get; set; }
        public string query1 { get; set; }
        public string query2 { get; set; }
        public int ID_empresa { get; set; }
    }
}
