//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Interna_CMKEntities : DbContext
    {
        public Interna_CMKEntities()
            : base("name=Interna_CMKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datos_Audit_11> Datos_Audit_11 { get; set; }
        public virtual DbSet<Datos_Marketing_Activity> Datos_Marketing_Activity { get; set; }
        public virtual DbSet<Estructura_1_1_Comercia> Estructura_1_1_Comercia { get; set; }
    }
}
