//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMRC
    {
        public short FirmCode { get; set; }
        public string FirmName { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
    }
}
