//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotions_v1
    {
        public int ID_datap { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string imgpath { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha { get; set; }
        public string query1 { get; set; }
    }
}
