//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_items
    {
        public int ID_stock { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public decimal quantity { get; set; }
        public System.DateTime odate { get; set; }
        public string ID_usuario { get; set; }
        public string comment { get; set; }
    }
}
