//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        public int ID_User { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public string Position { get; set; }
        public System.DateTime Registration_Date { get; set; }
        public bool Active { get; set; }
        public string Departments { get; set; }
        public string Roles { get; set; }
        public int ID_Company { get; set; }
        public string prop01 { get; set; }
        public string prop02 { get; set; }
        public string IDSAP { get; set; }
        public Nullable<decimal> BolsaValor { get; set; }
        public Nullable<decimal> PorcentajeBolsa { get; set; }
    }
}
