//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Surveys
    {
        public int ID_survey { get; set; }
        public string Brand { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Question1 { get; set; }
        public string Answer1 { get; set; }
        public string Question2 { get; set; }
        public string Answer2 { get; set; }
        public string Question3 { get; set; }
        public string Answer3 { get; set; }
        public string Question4 { get; set; }
        public string Answer4 { get; set; }
        public string Question5 { get; set; }
        public string Answer5 { get; set; }
        public string Question6 { get; set; }
        public string Answer6 { get; set; }
        public string Question7 { get; set; }
        public string Answer7 { get; set; }
        public string Question8 { get; set; }
        public string Answer8 { get; set; }
        public string Question9 { get; set; }
        public string Answer9 { get; set; }
        public string Question10 { get; set; }
        public string Answer10 { get; set; }
        public string Question11 { get; set; }
        public string Answer11 { get; set; }
        public string Question12 { get; set; }
        public string Answer12 { get; set; }
        public string Question13 { get; set; }
        public string Answer13 { get; set; }
        public string Question14 { get; set; }
        public string Answer14 { get; set; }
        public string Question15 { get; set; }
        public string Answer15 { get; set; }
        public string Question16 { get; set; }
        public string Answer16 { get; set; }
        public string Question17 { get; set; }
        public string Answer17 { get; set; }
        public string Question18 { get; set; }
        public string Answer18 { get; set; }
        public System.DateTime Date { get; set; }
    }
}
