//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_form_w9
    {
        public int ID_form { get; set; }
        public string name { get; set; }
        public string business_name { get; set; }
        public bool individual { get; set; }
        public bool ccorporation { get; set; }
        public bool scorporation { get; set; }
        public bool partnership { get; set; }
        public bool trust { get; set; }
        public bool limited { get; set; }
        public string tax_classification { get; set; }
        public bool other { get; set; }
        public string other_text { get; set; }
        public string exempt_payeecode { get; set; }
        public string exempt_fatcacode { get; set; }
        public string address { get; set; }
        public string city_state_zipcode { get; set; }
        public string list_account_nummber { get; set; }
        public string requestername_address { get; set; }
        public string social_securitynum { get; set; }
        public string employer_idnum { get; set; }
        public string signature { get; set; }
        public System.DateTime sigdate { get; set; }
        public bool iscomplete { get; set; }
        public int ID_usuario { get; set; }
    }
}
