//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Recursos_usuario = new HashSet<Recursos_usuario>();
        }
    
        public int ID_usuario { get; set; }
        public string correo { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string ID_clienteSAP { get; set; }
        public string NOM_clienteSAP { get; set; }
        public int ID_tipomembresia { get; set; }
        public Nullable<int> contador_visitas { get; set; }
        public Nullable<System.DateTime> fultima_visita { get; set; }
        public Nullable<System.DateTime> fcreacion_usuario { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Tipo_membresia Tipo_membresia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recursos_usuario> Recursos_usuario { get; set; }
    }
}
