//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitsM_representatives
    {
        public int ID_detalle { get; set; }
        public int ID_visit { get; set; }
        public int ID_usuario { get; set; }
        public string query1 { get; set; }
        public int ID_empresa { get; set; }
    
        public virtual VisitsM VisitsM { get; set; }
    }
}
