//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita_2_0
    {
        public string Id_Store { get; set; }
        public string Store { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> Id_Visit { get; set; }
        public string Cliente { get; set; }
        public string Marca { get; set; }
        public string LineaProducto { get; set; }
        public string MarcaCompetidorPrincipal { get; set; }
        public Nullable<decimal> CarasTiendaTotal { get; set; }
        public Nullable<decimal> CarasTiendaNuestraLinea { get; set; }
        public Nullable<decimal> CajasVentaCategMensual { get; set; }
        public string ProdExhibAlcancePublico { get; set; }
        public string ProductosOrganizados_Categoria { get; set; }
        public string ProductosOrganizados_Marca { get; set; }
        public string ProductosOrganizados_Sabor { get; set; }
        public string ProductosOrganizados_Otro { get; set; }
        public string AreaProducto_Limpia { get; set; }
        public string AreaProducto_Ordenada { get; set; }
        public string AreaProducto_Iluminada { get; set; }
        public string AreaProducto_Oscura { get; set; }
        public string AreaProducto_Suecia { get; set; }
        public string AreaProducto_Otro { get; set; }
        public string PrecioProducto_Visible { get; set; }
        public string PrecioProducto_Correcto { get; set; }
        public string PrecioProducto_NoVisible { get; set; }
        public string PrecioProducto_Incorrecto { get; set; }
        public string TiendaTieneMaterialPromocionalMarca { get; set; }
        public string TiendaTieneMaterialPromocionalProducto { get; set; }
        public string TiendaTieneEspacioMaterialPromocional { get; set; }
        public Nullable<decimal> TiendaTieneEspacioMaterialPromocional_Cuantos { get; set; }
        public string TiendaTieneEspacioMaterialPromocional_EndCap { get; set; }
        public string TiendaTieneEspacioMaterialPromocional_Gondola { get; set; }
        public string TiendaTieneEspacioMaterialPromocional_SideSeller { get; set; }
        public string TiendaTieneEspacioMaterialPromocional_IslandTables { get; set; }
        public string TiendaTieneEspacioMaterialPromocional_Stickers { get; set; }
        public string TiendaTieneEspacioMaterialPromocional_Preciadores { get; set; }
        public string TiendaTieneEspacioMaterialPromocional_Otro { get; set; }
        public string HerramientasDisplayTienda { get; set; }
        public string HerramientasDisplayTienda_EndCap { get; set; }
        public string HerramientasDisplayTienda_Gondola { get; set; }
        public string HerramientasDisplayTienda_SideSeller { get; set; }
        public string HerramientasDisplayTienda_IslandTables { get; set; }
        public string HerramientasDisplayTienda_Stickers { get; set; }
        public string HerramientasDisplayTienda_Preciadores { get; set; }
        public string HerramientasDisplayTienda_Otro { get; set; }
        public string HerramientasDisplayTienda_PresenciaDisplay_Excelente { get; set; }
        public string HerramientasDisplayTienda_PresenciaDisplay_Aceptable { get; set; }
        public string HerramientasDisplayTienda_PresenciaDisplay_Buena { get; set; }
        public string HerramientasDisplayTienda_PresenciaDisplay_Escasa { get; set; }
        public string AccesibProducto_MuyFacil { get; set; }
        public string AccesibProducto_Facil { get; set; }
        public string AccesibProducto_Dificil { get; set; }
        public string TieneProductoPrincipCompet { get; set; }
        public string TieneProductoCompiteProducto { get; set; }
        public string ProductoCompiteJuntoFisicamente { get; set; }
        public string UbicacionProductoCompetencia_Arriba { get; set; }
        public string UbicacionProductoCompetencia_Abajo { get; set; }
        public string UbicacionProductoCompetencia_Derecha { get; set; }
        public string UbicacionProductoCompetencia_Izquierda { get; set; }
        public string ProductoCompetHerramDisplay { get; set; }
        public string CompetenciaActivPromocionales { get; set; }
        public string VisitaClienteComproProducto { get; set; }
        public string ExistePosibColocarPromo { get; set; }
        public string TipoPromoPermiteColocar_Display { get; set; }
        public string TipoPromoPermiteColocar_Degustacion { get; set; }
        public string TipoPromoPermiteColocar_Regalia { get; set; }
        public string TipoPromoPermiteColocar_Otra { get; set; }
        public string ProgramoSegundaVisita { get; set; }
        public int ID_detail { get; set; }
    }
}
