//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciamarketing_webapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Script.Serialization;

    public partial class VisitsM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitsM()
        {
            this.VisitsM_representatives = new HashSet<VisitsM_representatives>();
        }

        public int ID_visit { get; set; }
        public string ID_customer { get; set; }
        public string customer { get; set; }
        public string ID_store { get; set; }
        public string store { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string state { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddTHH:mm}")]
        public System.DateTime visit_date { get; set; }
        public int ID_visitstate { get; set; }
        public string comments { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddTHH:mm}")]
        public System.DateTime check_in { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddTHH:mm}")]
        public System.DateTime check_out { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddTHH:mm}")]
        public System.DateTime end_date { get; set; }
        public string geoLong { get; set; }
        public string geoLat { get; set; }
        public int extra_hours { get; set; }
        public int ID_route { get; set; }
        public int ID_empresa { get; set; }

        [ScriptIgnore(ApplyToOverrides = true)]
        public virtual RoutesM RoutesM { get; set; }
        [ScriptIgnore(ApplyToOverrides = true)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitsM_representatives> VisitsM_representatives { get; set; }
    }
}
